language: scala
scala:
  - 2.12.7
jdk:
  - openjdk8
script:
  - sbt clean coverage fixCheck test coverageReport coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - >
    test "${TRAVIS_PULL_REQUEST}" = 'false' &&
    test "${TRAVIS_REPO_SLUG}" = 'radicalbit/nsdb-kafka-connect' &&
    sh "$TRAVIS_BUILD_DIR/travis-credentials.sh" &&
    sbt ++$TRAVIS_SCALA_VERSION publish